### ISSUE TITLE
please follow the official doc

### ISSUE THREAD

**Issue by mushfiqur-rahman** [ali09-github/Tailwind_project#1]
The command line of your JSON file is 
`"build": "tailwindcss -i ./src/input.css -o ./dist/output.css --watch"`
but in your project there has no `scr` folder included `input.css`. You used `style.css` in your root folder. so your command should be `tailwindcss -i style.css -o ./dist/output.css --watch`

Babel js extension need to installed.

**Comment by ali09-github** [comment]
ok let me check.

**Comment by ali09-github** [comment]
https://github.com/ali09-github/Personal_portfolio
Please look now I have fixed some problems but now CSS classes are not working.

**Comment by mushfiqur-rahman** [comment]
Bro, you have to practice html css first. Cause you do not understand the
file path. You kept your CSS in the main directory but you put the
command on package.json file *./dist/output.css.*
You have to understand file path/location first then try an
advanced framework.

**Comment by mushfiqur-rahman** [comment]
https://youtu.be/250R45w2xuQ
